"""
MCX Scanner (Scanner-3 MCX variant) — Configuration
=====================================================
All tunable constants live here. Edit this file to change thresholds,
commodities, or strike counts WITHOUT touching the core logic.

v2: Simplified per Logesh's request — CPR classification removed.
Alerts are now pure premium-spike + spot-trend, matching the Scanner-2
format. See mcx_scanner_main.py / telegram_notify.py.
"""

# ---------------------------------------------------------------------------
# Commodities to scan (MCX symbol as it appears in Upstox instrument master)
# ---------------------------------------------------------------------------
COMMODITIES = {
    "CRUDEOIL": {
        "upstox_symbol": "CRUDEOIL",
        "instrument_master_name": "CRUDE OIL",  # Upstox instrument master uses a space for this one
        "tradingsymbol_prefix": "CRUDEOIL",     # standard lot (excludes CRUDEOILM mini — see exclude below)
        "tradingsymbol_exclude_prefix": "CRUDEOILM",
        "min_move_rupees": 25,     # min premium move from day-open strike price to trigger alert
        "emoji": "🛢️",
    },
    "NATURALGAS": {
        "upstox_symbol": "NATURALGAS",
        "instrument_master_name": "NATURALGAS",
        "tradingsymbol_prefix": "NATURALGAS",   # standard lot (NATGASMINI is the separate mini line)
        "tradingsymbol_exclude_prefix": None,
        "min_move_rupees": 4.5,
        "emoji": "🔥",
    },
    "GOLD": {
        "upstox_symbol": "GOLD",
        "instrument_master_name": "GOLD",
        "tradingsymbol_prefix": "GOLDM",         # Mini — per Logesh's confirmation
        "tradingsymbol_exclude_prefix": None,
        "min_move_rupees": 35,
        "emoji": "🥇",
    },
    "SILVER": {
        "upstox_symbol": "SILVER",
        "instrument_master_name": "SILVER",
        "tradingsymbol_prefix": "SILVER",       # standard lot (excludes SILVERM mini — see exclude below)
        "tradingsymbol_exclude_prefix": "SILVERM",
        "min_move_rupees": 35,
        "emoji": "🥈",
    },
}

# Strikes tracked per side of the day's opening spot price
STRIKES_PER_SIDE_OTM = 5    # 5 OTM CE + 5 OTM PE
STRIKES_PER_SIDE_ITM = 5    # + 5 ITM CE + 5 ITM PE
# -> 10 CE + 10 PE = 20 strikes tracked per commodity

# MCX options are monthly expiry only (no weekly)
EXPIRY_CYCLE = "monthly"

# ---------------------------------------------------------------------------
# Volume spike alert (index/spot level)
# ---------------------------------------------------------------------------
VOLUME_AVG_LOOKBACK_DAYS = 18
VOLUME_SPIKE_MULTIPLIER = 1.5          # today's volume > 1.5x the 18-day avg => spike

# ---------------------------------------------------------------------------
# Telegram
# ---------------------------------------------------------------------------
TELEGRAM_BOT_TOKEN_ENV = "TELEGRAM_BOT_TOKEN"     # set as GitHub Actions secret
TELEGRAM_CHAT_ID_ENV = "TELEGRAM_CHAT_ID"

# ---------------------------------------------------------------------------
# Upstox
# ---------------------------------------------------------------------------
UPSTOX_ACCESS_TOKEN_ENV = "UPSTOX_ACCESS_TOKEN"   # generated by daily manual-login step
INSTRUMENT_MASTER_PATH = "instruments/mcx_instruments.csv"  # downloaded from Upstox instrument master
