"""
MCX Scanner (Scanner-3 MCX variant) — Configuration
=====================================================
All tunable constants live here. Edit this file to change thresholds,
commodities, or strike counts WITHOUT touching the core logic.
"""

# ---------------------------------------------------------------------------
# Commodities to scan (MCX symbol as it appears in Upstox instrument master)
# ---------------------------------------------------------------------------
COMMODITIES = {
    "CRUDEOIL": {
        "upstox_symbol": "CRUDEOIL",
        "min_move_rupees": 10,     # min premium move from day-open strike price to trigger alert
        "strike_step": 50,         # typical MCX Crude Oil strike interval (verify against instrument master)
    },
    "NATURALGAS": {
        "upstox_symbol": "NATURALGAS",
        "min_move_rupees": 3,
        "strike_step": 5,
    },
    "GOLD": {
        "upstox_symbol": "GOLD",
        "min_move_rupees": 20,
        "strike_step": 50,
    },
    "SILVER": {
        "upstox_symbol": "SILVER",
        "min_move_rupees": 15,
        "strike_step": 100,
    },
}

# Number of OTM strikes on each side of the day's opening spot price
STRIKES_PER_SIDE = 10   # -> 10 CE + 10 PE per commodity

# MCX options are monthly expiry only (no weekly)
EXPIRY_CYCLE = "monthly"

# ---------------------------------------------------------------------------
# CPR settings
# ---------------------------------------------------------------------------
NARROW_CPR_LOOKBACK_DAYS = 14          # average CPR width lookback
NARROW_CPR_THRESHOLD_PCT = 0.35        # today's width < 35% of avg width => Narrow
WIDE_CPR_THRESHOLD_PCT = 1.5           # today's width > 150% of avg width => Wide

# 18-day average volume lookback for the index/spot volume-spike alert
VOLUME_AVG_LOOKBACK_DAYS = 18
VOLUME_SPIKE_MULTIPLIER = 1.5          # today's volume > 1.5x the 18-day avg => spike

# ---------------------------------------------------------------------------
# Telegram
# ---------------------------------------------------------------------------
TELEGRAM_BOT_TOKEN_ENV = "TELEGRAM_BOT_TOKEN"     # set as GitHub Actions secret
TELEGRAM_CHAT_ID_ENV = "TELEGRAM_CHAT_ID"

# ---------------------------------------------------------------------------
# Upstox
# ---------------------------------------------------------------------------
UPSTOX_ACCESS_TOKEN_ENV = "UPSTOX_ACCESS_TOKEN"   # generated by daily manual-login step
INSTRUMENT_MASTER_PATH = "instruments/mcx_instruments.csv"  # downloaded from Upstox instrument master
